import { lookup } from "node:dns/promises";
import { isIP } from "node:net";

// Captures load URLs typed by users, so without this the headless browser
// would happily screenshot file:///etc/passwd, localhost:8787, cloud metadata
// endpoints or anything else on the machine's private network and hand the
// image back. Every request the page makes (navigation, redirects,
// subresources) goes through isAllowedUrl via a Playwright route.

function isBlockedIPv4(address: string): boolean {
  const [a, b] = address.split(".").map(Number);
  return (
    a === 0 || // "this" network
    a === 10 || // private
    a === 127 || // loopback
    (a === 100 && b >= 64 && b <= 127) || // carrier-grade NAT
    (a === 169 && b === 254) || // link-local, incl. cloud metadata
    (a === 172 && b >= 16 && b <= 31) || // private
    (a === 192 && b === 168) || // private
    (a === 192 && b === 0) || // IETF protocol assignments
    (a === 198 && (b === 18 || b === 19)) || // benchmarking
    a >= 224 // multicast + reserved
  );
}

function isBlockedIPv6(address: string): boolean {
  const lower = address.toLowerCase();
  if (lower === "::" || lower === "::1") return true;

  // IPv4-mapped (::ffff:a.b.c.d) and NAT64 (64:ff9b::a.b.c.d) addresses
  // reach IPv4 hosts, so judge them by the embedded address.
  // URL parsing rewrites the dotted tail as two hextets (::ffff:a00:1).
  const embedded = lower.match(/^(?:::ffff:|64:ff9b::)(\d+\.\d+\.\d+\.\d+)$/);
  if (embedded) return isBlockedIPv4(embedded[1]);
  const embeddedHex = lower.match(/^(?:::ffff:|64:ff9b::)([0-9a-f]{1,4}):([0-9a-f]{1,4})$/);
  if (embeddedHex) {
    const high = parseInt(embeddedHex[1], 16);
    const low = parseInt(embeddedHex[2], 16);
    return isBlockedIPv4(`${high >> 8}.${high & 0xff}.${low >> 8}.${low & 0xff}`);
  }

  const firstHextet = parseInt(lower.split(":")[0] || "0", 16);
  return (
    (firstHextet & 0xfe00) === 0xfc00 || // unique local fc00::/7 (incl. Fly's fdaa:: private network)
    (firstHextet & 0xffc0) === 0xfe80 || // link-local fe80::/10
    (firstHextet & 0xff00) === 0xff00 // multicast ff00::/8
  );
}

function isBlockedAddress(address: string): boolean {
  return isIP(address) === 6 ? isBlockedIPv6(address) : isBlockedIPv4(address);
}

/**
 * True only for http(s) URLs whose host resolves exclusively to public
 * addresses. `cache` lets one capture's many subresource checks share lookups.
 */
export async function isAllowedUrl(
  rawUrl: string,
  cache: Map<string, Promise<boolean>> = new Map()
): Promise<boolean> {
  let url: URL;
  try {
    url = new URL(rawUrl);
  } catch {
    return false;
  }

  // data:/blob: are generated by the page itself and never leave the browser.
  if (url.protocol === "data:" || url.protocol === "blob:") return true;
  if (url.protocol !== "http:" && url.protocol !== "https:") return false;

  const hostname = url.hostname.replace(/^\[|\]$/g, "");
  let verdict = cache.get(hostname);
  if (!verdict) {
    verdict = resolvesPublicly(hostname);
    cache.set(hostname, verdict);
  }
  return verdict;
}

async function resolvesPublicly(hostname: string): Promise<boolean> {
  if (hostname === "localhost" || hostname.endsWith(".localhost") || hostname.endsWith(".internal")) {
    return false;
  }
  if (isIP(hostname)) return !isBlockedAddress(hostname);

  try {
    const addresses = await lookup(hostname, { all: true });
    return addresses.length > 0 && addresses.every(({ address }) => !isBlockedAddress(address));
  } catch {
    return false;
  }
}
